steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/planetal-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/planetal-backend:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/planetal-backend:$COMMIT_SHA'
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/planetal-backend:latest'
    id: 'push-image-latest'

  # Deploy to server via SSH
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SSH_KEY" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key $$SSH_USER@$$SSH_HOST << 'ENDSSH'
          cd $$DEPLOY_PATH
          docker-compose pull
          docker-compose down
          docker-compose up -d
          docker image prune -af
        ENDSSH
    secretEnv: ['SSH_KEY', 'SSH_USER', 'SSH_HOST', 'DEPLOY_PATH']
    id: 'deploy'

# Specify timeout
timeout: '1200s'

# Substitutions (set in Cloud Build trigger)
substitutions:
  _DEPLOY_PATH: '/root/planetal-backend'

# Available secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ssh-key/versions/latest
      env: 'SSH_KEY'
    - versionName: projects/$PROJECT_ID/secrets/ssh-user/versions/latest
      env: 'SSH_USER'
    - versionName: projects/$PROJECT_ID/secrets/ssh-host/versions/latest
      env: 'SSH_HOST'
    - versionName: projects/$PROJECT_ID/secrets/deploy-path/versions/latest
      env: 'DEPLOY_PATH'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/planetal-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/planetal-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
