"""Rename Media uploader_id to uploaded_by_id

Revision ID: 1297d0e69e81
Revises: 434f78f548df
Create Date: 2025-12-08 10:53:08.390087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1297d0e69e81'
down_revision = '434f78f548df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('uploaded_by_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_media_uploader_created'), table_name='media')
    op.drop_index(op.f('idx_media_uploader_id'), table_name='media')
    op.drop_index(op.f('idx_media_uploader_type'), table_name='media')
    op.create_index('idx_media_uploaded_by_created', 'media', ['uploaded_by_id', 'created_at'], unique=False)
    op.create_index('idx_media_uploaded_by_id', 'media', ['uploaded_by_id'], unique=False)
    op.create_index('idx_media_uploaded_by_type', 'media', ['uploaded_by_id', 'media_type'], unique=False)
    op.drop_constraint(op.f('media_uploader_id_fkey'), 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'users', ['uploaded_by_id'], ['id'])
    op.drop_column('media', 'uploader_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key(op.f('media_uploader_id_fkey'), 'media', 'users', ['uploader_id'], ['id'])
    op.drop_index('idx_media_uploaded_by_type', table_name='media')
    op.drop_index('idx_media_uploaded_by_id', table_name='media')
    op.drop_index('idx_media_uploaded_by_created', table_name='media')
    op.create_index(op.f('idx_media_uploader_type'), 'media', ['uploader_id', 'media_type'], unique=False)
    op.create_index(op.f('idx_media_uploader_id'), 'media', ['uploader_id'], unique=False)
    op.create_index(op.f('idx_media_uploader_created'), 'media', ['uploader_id', 'created_at'], unique=False)
    op.drop_column('media', 'uploaded_by_id')
    # ### end Alembic commands ###
