"""add_paystack_fields

Revision ID: 319423217dda
Revises: 638069de359a
Create Date: 2025-12-19 21:26:29.019734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319423217dda'
down_revision = '638069de359a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add Paystack fields to subscription_plans
    op.add_column('subscription_plans', sa.Column('paystack_plan_code_monthly', sa.String(length=100), nullable=True))
    op.add_column('subscription_plans', sa.Column('paystack_plan_code_yearly', sa.String(length=100), nullable=True))
    op.create_index('idx_paystack_plan_monthly', 'subscription_plans', ['paystack_plan_code_monthly'], unique=False)
    op.create_index('idx_paystack_plan_yearly', 'subscription_plans', ['paystack_plan_code_yearly'], unique=False)
    
    # Add Paystack fields to user_subscriptions
    op.add_column('user_subscriptions', sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True))
    op.add_column('user_subscriptions', sa.Column('paystack_customer_code', sa.String(length=100), nullable=True))
    op.add_column('user_subscriptions', sa.Column('paystack_email_token', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_paystack_subscription_code', 'user_subscriptions', ['paystack_subscription_code'])
    op.create_index('idx_paystack_subscription', 'user_subscriptions', ['paystack_subscription_code'], unique=False)
    op.create_index('idx_paystack_customer', 'user_subscriptions', ['paystack_customer_code'], unique=False)
    
    # Add Paystack fields to subscription_payments
    op.add_column('subscription_payments', sa.Column('paystack_reference', sa.String(length=100), nullable=True))
    op.add_column('subscription_payments', sa.Column('paystack_authorization_code', sa.String(length=100), nullable=True))
    op.add_column('subscription_payments', sa.Column('paystack_access_code', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_paystack_reference', 'subscription_payments', ['paystack_reference'])
    op.create_index('idx_paystack_reference', 'subscription_payments', ['paystack_reference'], unique=False)
    op.create_index('idx_paystack_authorization', 'subscription_payments', ['paystack_authorization_code'], unique=False)
    
    # Create paystack_event_logs table
    op.create_table(
        'paystack_event_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('event_id', sa.String(length=100), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=True),
        sa.Column('processing_status', sa.String(length=50), nullable=False),
        sa.Column('event_metadata', sa.Text(), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_paystack_event_id', 'paystack_event_logs', ['event_id'], unique=False)
    op.create_index('idx_paystack_event_type', 'paystack_event_logs', ['event_type'], unique=False)
    op.create_index('idx_paystack_processing_status', 'paystack_event_logs', ['processing_status'], unique=False)
    op.create_index('idx_paystack_processed_at', 'paystack_event_logs', ['processed_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop paystack_event_logs table
    op.drop_index('idx_paystack_processed_at', table_name='paystack_event_logs')
    op.drop_index('idx_paystack_processing_status', table_name='paystack_event_logs')
    op.drop_index('idx_paystack_event_type', table_name='paystack_event_logs')
    op.drop_index('idx_paystack_event_id', table_name='paystack_event_logs')
    op.drop_table('paystack_event_logs')
    
    # Remove Paystack fields from subscription_payments
    op.drop_index('idx_paystack_authorization', table_name='subscription_payments')
    op.drop_index('idx_paystack_reference', table_name='subscription_payments')
    op.drop_constraint('uq_paystack_reference', 'subscription_payments', type_='unique')
    op.drop_column('subscription_payments', 'paystack_access_code')
    op.drop_column('subscription_payments', 'paystack_authorization_code')
    op.drop_column('subscription_payments', 'paystack_reference')
    
    # Remove Paystack fields from user_subscriptions
    op.drop_index('idx_paystack_customer', table_name='user_subscriptions')
    op.drop_index('idx_paystack_subscription', table_name='user_subscriptions')
    op.drop_constraint('uq_paystack_subscription_code', 'user_subscriptions', type_='unique')
    op.drop_column('user_subscriptions', 'paystack_email_token')
    op.drop_column('user_subscriptions', 'paystack_customer_code')
    op.drop_column('user_subscriptions', 'paystack_subscription_code')
    
    # Remove Paystack fields from subscription_plans
    op.drop_index('idx_paystack_plan_yearly', table_name='subscription_plans')
    op.drop_index('idx_paystack_plan_monthly', table_name='subscription_plans')
    op.drop_column('subscription_plans', 'paystack_plan_code_yearly')
    op.drop_column('subscription_plans', 'paystack_plan_code_monthly')
    
    # ### end Alembic commands ###

