"""Rename task assignee_id to assigned_to_id

Revision ID: 434f78f548df
Revises: 59a72536dd76
Create Date: 2025-12-08 10:35:27.040784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434f78f548df'
down_revision = '59a72536dd76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes if they exist (using IF EXISTS to avoid transaction errors)
    op.execute('DROP INDEX IF EXISTS idx_event_creator_date_status')
    op.execute('DROP INDEX IF EXISTS idx_event_date_location_type')
    op.execute('DROP INDEX IF EXISTS idx_notification_user_type_status')
    
    op.add_column('tasks', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    
    op.execute('DROP INDEX IF EXISTS idx_task_assignee_id')
    op.create_index('idx_task_assignee_id', 'tasks', ['assigned_to_id'], unique=False)
    
    op.execute('DROP INDEX IF EXISTS idx_task_assignee_status')
    op.create_index('idx_task_assignee_status', 'tasks', ['assigned_to_id', 'status'], unique=False)
    
    # Drop constraint if exists (postgres syntax)
    op.execute('ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_assignee_id_fkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to_id'], ['id'])
    
    # Check if column exists before dropping
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name='tasks' AND column_name='assignee_id'"
    ))
    if result.fetchone():
        op.drop_column('tasks', 'assignee_id')
    
    op.execute('DROP INDEX IF EXISTS idx_timeline_event_status')
    op.execute('DROP INDEX IF EXISTS idx_user_location_active')
    op.execute('DROP INDEX IF EXISTS idx_vendor_booking_date_status_vendor')
    op.execute('DROP INDEX IF EXISTS idx_vendor_category_rating_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vendor_category_rating_location'), 'vendors', ['category', 'average_rating', 'city'], unique=False)
    op.create_index(op.f('idx_vendor_booking_date_status_vendor'), 'vendor_bookings', ['service_date', 'status', 'vendor_id'], unique=False)
    op.create_index(op.f('idx_user_location_active'), 'users', ['city', 'country', 'is_active'], unique=False)
    op.create_index(op.f('idx_timeline_event_status'), 'timeline_items', ['timeline_id', 'status'], unique=False)
    op.add_column('tasks', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_index('idx_task_assignee_status', table_name='tasks')
    op.create_index(op.f('idx_task_assignee_status'), 'tasks', ['assignee_id', 'status'], unique=False)
    op.drop_index('idx_task_assignee_id', table_name='tasks')
    op.create_index(op.f('idx_task_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.drop_column('tasks', 'assigned_to_id')
    op.create_index(op.f('idx_notification_user_type_status'), 'notification_logs', ['recipient_id', 'notification_type', 'status'], unique=False)
    op.create_index(op.f('idx_event_date_location_type'), 'events', ['start_datetime', 'venue_city', 'event_type'], unique=False)
    op.create_index(op.f('idx_event_creator_date_status'), 'events', ['creator_id', 'start_datetime', 'status'], unique=False)
    # ### end Alembic commands ###
