"""Add calendar tables - fixed base

Revision ID: 59a72536dd76
Revises: ac472774a00b
Create Date: 2025-12-08 10:11:40.066345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a72536dd76'
down_revision = 'ac472774a00b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'APPLE', 'OUTLOOK', name='calendarproviderenum'), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('calendar_name', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCING', 'SYNCED', 'FAILED', 'DISABLED', name='syncstatusenum'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error_message', sa.Text(), nullable=True),
    sa.Column('sync_error_count', sa.Integer(), nullable=False),
    sa.Column('sync_direction', sa.String(length=20), nullable=False),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_connections_expires_at', 'calendar_connections', ['expires_at'], unique=False)
    op.create_index('idx_calendar_connections_last_sync_at', 'calendar_connections', ['last_sync_at'], unique=False)
    op.create_index('idx_calendar_connections_provider', 'calendar_connections', ['provider'], unique=False)
    op.create_index('idx_calendar_connections_sync_enabled', 'calendar_connections', ['sync_enabled'], unique=False)
    op.create_index('idx_calendar_connections_sync_enabled_status', 'calendar_connections', ['sync_enabled', 'sync_status'], unique=False)
    op.create_index('idx_calendar_connections_sync_status', 'calendar_connections', ['sync_status'], unique=False)
    op.create_index('idx_calendar_connections_user_id', 'calendar_connections', ['user_id'], unique=False)
    op.create_index('idx_calendar_connections_user_provider', 'calendar_connections', ['user_id', 'provider'], unique=False)
    op.create_index('idx_calendar_connections_user_sync_enabled', 'calendar_connections', ['user_id', 'sync_enabled'], unique=False)
    op.create_index(op.f('ix_calendar_connections_id'), 'calendar_connections', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_connection_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('recurrence_parent_id', sa.Integer(), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('external_etag', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCING', 'SYNCED', 'FAILED', 'DISABLED', name='syncstatusenum'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurrence_parent_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_events_all_day', 'calendar_events', ['all_day'], unique=False)
    op.create_index('idx_calendar_events_connection_id', 'calendar_events', ['calendar_connection_id'], unique=False)
    op.create_index('idx_calendar_events_end_time', 'calendar_events', ['end_time'], unique=False)
    op.create_index('idx_calendar_events_external_connection', 'calendar_events', ['external_event_id', 'calendar_connection_id'], unique=False)
    op.create_index('idx_calendar_events_external_id', 'calendar_events', ['external_event_id'], unique=False)
    op.create_index('idx_calendar_events_last_synced_at', 'calendar_events', ['last_synced_at'], unique=False)
    op.create_index('idx_calendar_events_recurrence_parent_id', 'calendar_events', ['recurrence_parent_id'], unique=False)
    op.create_index('idx_calendar_events_start_time', 'calendar_events', ['start_time'], unique=False)
    op.create_index('idx_calendar_events_sync_status', 'calendar_events', ['sync_status'], unique=False)
    op.create_index('idx_calendar_events_time_range', 'calendar_events', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_calendar_events_user_end_time', 'calendar_events', ['user_id', 'end_time'], unique=False)
    op.create_index('idx_calendar_events_user_id', 'calendar_events', ['user_id'], unique=False)
    op.create_index('idx_calendar_events_user_time', 'calendar_events', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_table('calendar_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_connection_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('sync_direction', sa.String(length=20), nullable=False),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCING', 'SYNCED', 'FAILED', 'DISABLED', name='syncstatusenum'), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('events_deleted', sa.Integer(), nullable=False),
    sa.Column('events_skipped', sa.Integer(), nullable=False),
    sa.Column('sync_started_at', sa.DateTime(), nullable=False),
    sa.Column('sync_completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_sync_logs_completed_at', 'calendar_sync_logs', ['sync_completed_at'], unique=False)
    op.create_index('idx_calendar_sync_logs_connection_id', 'calendar_sync_logs', ['calendar_connection_id'], unique=False)
    op.create_index('idx_calendar_sync_logs_connection_started', 'calendar_sync_logs', ['calendar_connection_id', 'sync_started_at'], unique=False)
    op.create_index('idx_calendar_sync_logs_started_at', 'calendar_sync_logs', ['sync_started_at'], unique=False)
    op.create_index('idx_calendar_sync_logs_status', 'calendar_sync_logs', ['sync_status'], unique=False)
    op.create_index('idx_calendar_sync_logs_status_started', 'calendar_sync_logs', ['sync_status', 'sync_started_at'], unique=False)
    op.create_index('idx_calendar_sync_logs_sync_type', 'calendar_sync_logs', ['sync_type'], unique=False)
    op.create_index(op.f('ix_calendar_sync_logs_id'), 'calendar_sync_logs', ['id'], unique=False)
    op.create_table('calendar_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_connection_id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.String(length=255), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_uri', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_connection_id'], ['calendar_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_webhooks_active', 'calendar_webhooks', ['is_active'], unique=False)
    op.create_index('idx_calendar_webhooks_active_expires', 'calendar_webhooks', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_calendar_webhooks_connection_id', 'calendar_webhooks', ['calendar_connection_id'], unique=False)
    op.create_index('idx_calendar_webhooks_expires_at', 'calendar_webhooks', ['expires_at'], unique=False)
    op.create_index('idx_calendar_webhooks_webhook_id', 'calendar_webhooks', ['webhook_id'], unique=False)
    op.create_index(op.f('ix_calendar_webhooks_id'), 'calendar_webhooks', ['id'], unique=False)
    op.create_table('calendar_event_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('response_status', sa.String(length=20), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('external_attendee_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_event_attendees_email', 'calendar_event_attendees', ['email'], unique=False)
    op.create_index('idx_calendar_event_attendees_event_id', 'calendar_event_attendees', ['calendar_event_id'], unique=False)
    op.create_index('idx_calendar_event_attendees_event_response', 'calendar_event_attendees', ['calendar_event_id', 'response_status'], unique=False)
    op.create_index('idx_calendar_event_attendees_is_organizer', 'calendar_event_attendees', ['is_organizer'], unique=False)
    op.create_index('idx_calendar_event_attendees_response_status', 'calendar_event_attendees', ['response_status'], unique=False)
    op.create_index(op.f('ix_calendar_event_attendees_id'), 'calendar_event_attendees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_event_attendees_id'), table_name='calendar_event_attendees')
    op.drop_index('idx_calendar_event_attendees_response_status', table_name='calendar_event_attendees')
    op.drop_index('idx_calendar_event_attendees_is_organizer', table_name='calendar_event_attendees')
    op.drop_index('idx_calendar_event_attendees_event_response', table_name='calendar_event_attendees')
    op.drop_index('idx_calendar_event_attendees_event_id', table_name='calendar_event_attendees')
    op.drop_index('idx_calendar_event_attendees_email', table_name='calendar_event_attendees')
    op.drop_table('calendar_event_attendees')
    op.drop_index(op.f('ix_calendar_webhooks_id'), table_name='calendar_webhooks')
    op.drop_index('idx_calendar_webhooks_webhook_id', table_name='calendar_webhooks')
    op.drop_index('idx_calendar_webhooks_expires_at', table_name='calendar_webhooks')
    op.drop_index('idx_calendar_webhooks_connection_id', table_name='calendar_webhooks')
    op.drop_index('idx_calendar_webhooks_active_expires', table_name='calendar_webhooks')
    op.drop_index('idx_calendar_webhooks_active', table_name='calendar_webhooks')
    op.drop_table('calendar_webhooks')
    op.drop_index(op.f('ix_calendar_sync_logs_id'), table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_sync_type', table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_status_started', table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_status', table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_started_at', table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_connection_started', table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_connection_id', table_name='calendar_sync_logs')
    op.drop_index('idx_calendar_sync_logs_completed_at', table_name='calendar_sync_logs')
    op.drop_table('calendar_sync_logs')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index('idx_calendar_events_user_time', table_name='calendar_events')
    op.drop_index('idx_calendar_events_user_id', table_name='calendar_events')
    op.drop_index('idx_calendar_events_user_end_time', table_name='calendar_events')
    op.drop_index('idx_calendar_events_time_range', table_name='calendar_events')
    op.drop_index('idx_calendar_events_sync_status', table_name='calendar_events')
    op.drop_index('idx_calendar_events_start_time', table_name='calendar_events')
    op.drop_index('idx_calendar_events_recurrence_parent_id', table_name='calendar_events')
    op.drop_index('idx_calendar_events_last_synced_at', table_name='calendar_events')
    op.drop_index('idx_calendar_events_external_id', table_name='calendar_events')
    op.drop_index('idx_calendar_events_external_connection', table_name='calendar_events')
    op.drop_index('idx_calendar_events_end_time', table_name='calendar_events')
    op.drop_index('idx_calendar_events_connection_id', table_name='calendar_events')
    op.drop_index('idx_calendar_events_all_day', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_calendar_connections_id'), table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_user_sync_enabled', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_user_provider', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_user_id', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_sync_status', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_sync_enabled_status', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_sync_enabled', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_provider', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_last_sync_at', table_name='calendar_connections')
    op.drop_index('idx_calendar_connections_expires_at', table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
