"""add_qr_code_url_to_invite_links

Revision ID: 638069de359a
Revises: 66eed6c50eab
Create Date: 2025-12-13 15:53:57.184697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638069de359a'
down_revision = '66eed6c50eab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_event_creator_date_status')
    op.execute('DROP INDEX IF EXISTS idx_event_date_location_type')
    op.add_column('invite_links', sa.Column('qr_code_url', sa.String(length=500), nullable=True))
    op.execute('DROP INDEX IF EXISTS idx_notification_user_type_status')
    op.execute('DROP INDEX IF EXISTS idx_timeline_event_status')
    op.execute('DROP INDEX IF EXISTS idx_user_location_active')
    op.execute('DROP INDEX IF EXISTS idx_vendor_booking_date_status_vendor')
    op.execute('DROP INDEX IF EXISTS idx_vendor_category_rating_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vendor_category_rating_location'), 'vendors', ['category', 'average_rating', 'city'], unique=False)
    op.create_index(op.f('idx_vendor_booking_date_status_vendor'), 'vendor_bookings', ['service_date', 'status', 'vendor_id'], unique=False)
    op.create_index(op.f('idx_user_location_active'), 'users', ['city', 'country', 'is_active'], unique=False)
    op.create_index(op.f('idx_timeline_event_status'), 'timeline_items', ['timeline_id', 'status'], unique=False)
    op.create_index(op.f('idx_notification_user_type_status'), 'notification_logs', ['recipient_id', 'notification_type', 'status'], unique=False)
    op.drop_column('invite_links', 'qr_code_url')
    op.create_index(op.f('idx_event_date_location_type'), 'events', ['start_datetime', 'venue_city', 'event_type'], unique=False)
    op.create_index(op.f('idx_event_creator_date_status'), 'events', ['creator_id', 'start_datetime', 'status'], unique=False)
    # ### end Alembic commands ###
