"""Add recipient_id to ContactInvitation

Revision ID: 66eed6c50eab
Revises: 1297d0e69e81
Create Date: 2025-12-08 10:59:05.897703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eed6c50eab'
down_revision = '1297d0e69e81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_invitations', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact_invitations', 'users', ['recipient_id'], ['id'])
    op.drop_index(op.f('idx_event_creator_date_status'), table_name='events')
    op.drop_index(op.f('idx_event_date_location_type'), table_name='events')
    op.drop_index(op.f('idx_notification_user_type_status'), table_name='notification_logs')
    op.drop_index(op.f('idx_timeline_event_status'), table_name='timeline_items')
    op.drop_index(op.f('idx_user_location_active'), table_name='users')
    op.drop_index(op.f('idx_vendor_booking_date_status_vendor'), table_name='vendor_bookings')
    op.drop_index(op.f('idx_vendor_category_rating_location'), table_name='vendors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vendor_category_rating_location'), 'vendors', ['category', 'average_rating', 'city'], unique=False)
    op.create_index(op.f('idx_vendor_booking_date_status_vendor'), 'vendor_bookings', ['service_date', 'status', 'vendor_id'], unique=False)
    op.create_index(op.f('idx_user_location_active'), 'users', ['city', 'country', 'is_active'], unique=False)
    op.create_index(op.f('idx_timeline_event_status'), 'timeline_items', ['timeline_id', 'status'], unique=False)
    op.create_index(op.f('idx_notification_user_type_status'), 'notification_logs', ['recipient_id', 'notification_type', 'status'], unique=False)
    op.create_index(op.f('idx_event_date_location_type'), 'events', ['start_datetime', 'venue_city', 'event_type'], unique=False)
    op.create_index(op.f('idx_event_creator_date_status'), 'events', ['creator_id', 'start_datetime', 'status'], unique=False)
    op.drop_constraint(None, 'contact_invitations', type_='foreignkey')
    op.drop_column('contact_invitations', 'recipient_id')
    # ### end Alembic commands ###
