"""Add payment idempotency keys table

Revision ID: 80cb8398b4e3
Revises: 20260103_1200
Create Date: 2026-01-06 20:49:30.030873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '80cb8398b4e3'
down_revision = '20260103_1200'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists"""
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()

def index_exists(index_name, table_name):
    """Check if an index exists"""
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create payment_idempotency_keys table (if not exists)
    if not table_exists('payment_idempotency_keys'):
        op.create_table('payment_idempotency_keys',
            sa.Column('key', sa.String(length=255), nullable=False),
            sa.Column('resource_type', sa.String(length=100), nullable=False),
            sa.Column('resource_id', sa.String(length=255), nullable=True),
            sa.Column('request_hash', sa.String(length=64), nullable=False),
            sa.Column('response_data', sa.Text(), nullable=True),
            sa.Column('is_completed', sa.Boolean(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('key')
        )
    
    # Create indexes for payment_idempotency_keys (if not exists)
    if not index_exists('idx_payment_idempotency_expires', 'payment_idempotency_keys'):
        op.create_index('idx_payment_idempotency_expires', 'payment_idempotency_keys', ['expires_at'], unique=False)
    if not index_exists('idx_payment_idempotency_key', 'payment_idempotency_keys'):
        op.create_index('idx_payment_idempotency_key', 'payment_idempotency_keys', ['key'], unique=False)
    if not index_exists('idx_payment_idempotency_resource', 'payment_idempotency_keys'):
        op.create_index('idx_payment_idempotency_resource', 'payment_idempotency_keys', ['resource_type', 'resource_id'], unique=False)
    if not index_exists('ix_payment_idempotency_keys_key', 'payment_idempotency_keys'):
        op.create_index(op.f('ix_payment_idempotency_keys_key'), 'payment_idempotency_keys', ['key'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    if index_exists('ix_payment_idempotency_keys_key', 'payment_idempotency_keys'):
        op.drop_index(op.f('ix_payment_idempotency_keys_key'), table_name='payment_idempotency_keys')
    if index_exists('idx_payment_idempotency_resource', 'payment_idempotency_keys'):
        op.drop_index('idx_payment_idempotency_resource', table_name='payment_idempotency_keys')
    if index_exists('idx_payment_idempotency_key', 'payment_idempotency_keys'):
        op.drop_index('idx_payment_idempotency_key', table_name='payment_idempotency_keys')
    if index_exists('idx_payment_idempotency_expires', 'payment_idempotency_keys'):
        op.drop_index('idx_payment_idempotency_expires', table_name='payment_idempotency_keys')
    
    # Drop table
    if table_exists('payment_idempotency_keys'):
        op.drop_table('payment_idempotency_keys')
    
    # ### end Alembic commands ###
