"""Add calendar tables

Revision ID: ac472774a00b
Revises: 653c259aeb07
Create Date: 2025-12-08 09:19:27.568767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac472774a00b'
down_revision = '653c259aeb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
